// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCr1mW8ZkXu6ASnUUr6-M5t3wuij-PtLVc',
    appId: '1:849603868084:android:b56bb17555e3c06a736ee1',
    messagingSenderId: '849603868084',
    projectId: 'uni-bite-17c65',
    storageBucket: 'uni-bite-17c65.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuO-5HAWHfAj1bpOf2jjb2TeP4z8YMOoA',
    appId: '1:849603868084:ios:0fd1d057bc82f03c736ee1',
    messagingSenderId: '849603868084',
    projectId: 'uni-bite-17c65',
    storageBucket: 'uni-bite-17c65.firebasestorage.app',
    androidClientId: '849603868084-oc51gt8en3bl2j97v3nsfpr92hoi2t6r.apps.googleusercontent.com',
    iosClientId: '849603868084-0a11h0hb1054gcfinl1vfbjcdu5o20on.apps.googleusercontent.com',
    iosBundleId: 'com.example.uniBite',
  );
}
